from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.login_view, name='home'),  # Login page as home
    path('home/', views.home, name='home_page'),  # Actual home page after login
    path('about/', views.about, name='about'),
    path('membership/', views.membership, name='membership'),
    path('announcements/', views.announcements, name='announcements'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('user-dashboard/', views.user_dashboard, name='user_dashboard'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('meetings/', views.meetings, name='meetings'),
    path('claims/', views.claims, name='claims'),
    path('shares/', views.shares, name='shares'),
    path('payments/', views.payments, name='payments'),
    path('profile/', views.profile, name='profile'),
    path('upgrade/', views.upgrade, name='upgrade'),
    path('single-application/', views.single_application, name='single_application'),
    path('double-application/', views.double_application_view, name='double_application'),
    path('deduct-shares/', views.deduct_all_shares, name='deduct_shares'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('activate-user/<int:user_id>/', views.activate_user, name='activate_user'),
    path('user-details/<int:user_id>/', views.user_details, name='user_details'),
    path('admin-meetings/', views.admin_meetings, name='admin_meetings'),
    path('admin-announcements/', views.admin_announcements, name='admin_announcements'),
    path('edit-meeting/<int:meeting_id>/', views.edit_meeting, name='edit_meeting'),
    path('delete-meeting/<int:meeting_id>/', views.delete_meeting, name='delete_meeting'),
    path('edit-announcement/<int:announcement_id>/', views.edit_announcement, name='edit_announcement'),
    path('delete-announcement/<int:announcement_id>/', views.delete_announcement, name='delete_announcement'),
    path('my-applications/', views.my_applications, name='my_applications'),
    path('my-claims/', views.my_claims, name='my_claims'),
    path('mark-notification-read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('clear-notifications/', views.clear_notifications, name='clear_notifications'),
    path('delete-notification/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('print-financial-report/', views.print_financial_report, name='print_financial_report'),
    path('print-shares-report/', views.print_shares_report, name='print_shares_report'),
    path('print-members-report/', views.print_members_report, name='print_members_report'),
    path('print-claims-report/', views.print_claims_report, name='print_claims_report'),
    path('review-application/<int:app_id>/', views.review_application, name='review_application'),
    path('review-payment/<int:payment_id>/', views.review_payment, name='review_payment'),
    path('review-claim/<int:claim_id>/', views.review_claim, name='review_claim'),
    path('review-share/<int:share_id>/', views.review_share, name='review_share'),
    path('view-message/<int:message_id>/', views.view_message, name='view_message'),
    path('user-inbox/', views.user_inbox, name='user_inbox'),
    path('send-message/', views.send_message_to_admin, name='send_message_to_admin'),
    path('admin-applications/', views.admin_applications, name='admin_applications'),
    path('admin-payments/', views.admin_payments, name='admin_payments'),
    path('admin-claims/', views.admin_claims, name='admin_claims'),
    path('admin-shares/', views.admin_shares, name='admin_shares'),
    path('admin-messages/', views.admin_messages, name='admin_messages'),
    path('admin-notifications/', views.admin_notifications, name='admin_notifications'),
    path('admin-deduction-history/', views.admin_deduction_history, name='admin_deduction_history'),
    path('notifications/', views.notifications, name='notifications'),
    path('delete-all-notifications/', views.delete_all_notifications, name='delete_all_notifications'),
    path('admin-create-notification/', views.admin_create_notification, name='admin_create_notification'),
    path('reply-message/<int:message_id>/', views.reply_message, name='reply_message'),
    path('user-profile/', views.user_profile, name='user_profile'),
    path('constitution/', views.constitution_page, name='constitution'),
    path('serve-constitution/', views.serve_constitution, name='serve_constitution'),
    path('trigger-monthly-deduction/', views.trigger_monthly_deduction, name='trigger_monthly_deduction'),
]